- hosts: all
  roles:
         # Loads library/openshift.py to make it available to other plays;
         # does nothing else by itself
         - { role: epfl_idevelop.ansible_module_openshift }

- hosts: all
  tasks:
    - name: "Route"
      openshift:
        state: absent
        kind: Route
        name: "nginx-route"
        namespace: "myproject"
        content: |
            apiVersion: v1
            kind: Route
            metadata:
                name: my-nginx-app
            spec:
                host: my-nginx-app-myproject.192.168.99.100.nip.io
                port:
                    targetPort: 80
                to:
                    kind: Service
                    name: my-nginx-app

    - name: "deployment config"
      openshift:
        state: absent
        kind: DeploymentConfig
        name: "nginx-dep1"
        namespace: "my-project"
        content: |
            kind: "DeploymentConfig"
            apiVersion: "v1"
            metadata:
                name: my-nginx-app
                labels:
                    run: my-nginx-app
                namespace: myproject
            spec:
                template:
                    metadata:
                        labels:
                            run: my-nginx-app
                    spec:
                        containers:
                            - name: helloworld
                              image: nginx
                              ports:
                                - containerPort: 80
                                  protocol: "TCP"
                replicas: 1
                selector:
                    run: my-nginx-app
                triggers:
                    - type: "ConfigChange"

    - name: "Service"
      openshift:
        state: absent
        kind: Service
        name: "nginx-svc"
        namespace: "my-project"
        content: |
            apiVersion: v1
            kind: Service
            metadata:
                name: my-nginx-app
                labels:
                   run: my-nginx-app
                namespace: myproject
            spec:
                selector:
                   run: my-nginx-app
                ports:
                - port: 80
                  protocol: TCP
                  targetPort: 8080