apiVersion: v1
kind: Service
metadata:
    name: my-nginx-app
    labels:
      run: my-nginx-app
    namespace: myproject
spec:
    selector:
        run: my-nginx-app
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
