---
- hosts: localhost
  roles:
         # Loads library/openshift.py to make it available to other plays;
         # does nothing else by itself
         - { role: epfl_idevelop.ansible_module_openshift }

- hosts: localhost
  vars:
    replicas: 1
  tasks:
    - name: "deployment config"
      openshift:
        state: "{{state}}"
        kind: DeploymentConfig
        name: "nginx-dep1"
        namespace: "myproject"
        content: |
            kind: "DeploymentConfig"
            apiVersion: "v1"
            metadata:
                name: {{dpl_name}}
                labels:
                    run: {{dpl_name}}
                namespace: myproject
            spec:
                template:
                    metadata:
                        labels:
                            run: {{dpl_name}}
                    spec:
                        containers:
                            - name: helloworld
                              image: nginx
                              ports:
                                - containerPort: 80
                                  protocol: "TCP"
                replicas: {{replicas}}
                selector:
                    run: {{dpl_name}}
                triggers:
                    - type: "ConfigChange"