---
- hosts: localhost
  roles:
         # Loads library/openshift.py to make it available to other plays;
         # does nothing else by itself
         - { role: epfl_idevelop.ansible_module_openshift }

- hosts: localhost
  tasks:
    - name: "Service"
      openshift:
        state: "{{state}}"
        kind: Service
        name: "nginx-svc"
        namespace: "my-project"
        content: |
            apiVersion: v1
            kind: Service
            metadata:
                name: {{dpl_name}}
                labels:
                   run: {{dpl_name}}
                namespace: myproject
            spec:
                selector:
                   run: {{dpl_name}}
                ports:
                - port: 80
                  protocol: TCP
                  targetPort: 80