apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-bat
  labels:
      id: bat
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /op
    server: 128.179.146.8
    readOnly: false

