---
- hosts: localhost
  vars:
    replicas: 1
    db_ip: 128.179.146.8
    db_name: db1
    app_name: opp-app
  tasks:
    - name: "deployment config"
      openshift:
        state: "{{state}}"
        kind: DeploymentConfig
        name: "{{app_name}}"
        namespace: "myproject"
        apiVersion: apps.openshift.io/v1
        metadata:
          labels:
            run: "{{app_name}}"
          name: "{{app_name}}"
          namespace: myproject

        spec:
          replicas: "{{replicas}}"
          revisionHistoryLimit: 10
          selector:
            run: "{{app_name}}"
          template:
            metadata:
              labels:
                run: "{{app_name}}"
            spec:
              containers:
                - env:
                    - name: DATABASE_URL
                      value: 'mysql2://root:root!@{{db_ip}}:3306/"{{db_name}}"'
                  image: 'openproject/community:9'
                  name: "{{app_name}}"
                  volumeMounts:
                    - mountPath: /usr/share/ops
                      name: nfsvol-2
              volumes:
                - name: nfsvol-2
                  persistentVolumeClaim:
                    claimName: nfs-pvc
          triggers:
            - type: ConfigChange
