---
- hosts: localhost
  roles:
         # Loads library/openshift.py to make it available to other plays;
         # does nothing else by itself
         - { role: epfl_idevelop.ansible_module_openshift }

- hosts: localhost
  vars:
    nfs_ip: 128.179.146.8
  tasks:
    - name: "PersistentVolume"
      openshift:
        as_admin: true
        state: "{{state}}"
        kind: PersistentVolume
        name: "nfs-pv-bat"
        namespace: "myproject"
        content: |
            apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: nfs-pv-bat
              labels:
                  id: bat
            spec:
              capacity:
                storage: 1Gi
              accessModes:
                - ReadWriteMany
              persistentVolumeReclaimPolicy: Retain
              nfs:
                path: /
                server: {{dbip}}
                readOnly: false
