---
- hosts: localhost
  roles:
         # Loads library/openshift.py to make it available to other plays;
         # does nothing else by itself
         - { role: epfl_idevelop.ansible_module_openshift }

- hosts: localhost
  tasks:
    - name: "PersistentVolumeClaim"
      openshift:
        state: latest
        kind: PersistentVolumeClaim
        name: "nfs-pvc"
        namespace: "my-project"
        content: |
            apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: nfs-pvc  
            spec:
              accessModes:
              - ReadWriteMany      
              resources:
                 requests:
                   storage: 1Gi
              selector:
                  matchLabels:
                      id: bat